services:
  elasticsearch:
    extends:
      file: ./logging/elk-stack.yml
      service: elasticsearch

  logstash:
    extends:
      file: ./logging/elk-stack.yml
      service: logstash

  kibana:
    extends:
      file: ./logging/elk-stack.yml
      service: kibana
