services:
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: coffee-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - backend
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.1.0
    container_name: coffee-grafana
    ports:
      - "3008:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - backend
    restart: unless-stopped

volumes:
  grafana_data:

networks:
  backend:
    external: true
    name: microservices_backend
