apiVersion: v1
kind: Secret
metadata:
  name: coffee-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "replace-me"
  JWT_SECRET: "replace-me"
  INTERNAL_SERVICE_TOKEN: "replace-me"
  SMTP_HOST: "smtp.example.com"
  SMTP_USER: "noreply@example.com"
  SMTP_PASS: "replace-me"
  VNPAY_SECRET_KEY: "replace-me"
